# Fly.io configuration for Sunny Bot

app = "sunny-bot"
primary_region = "iad"

[build]
  [build.args]
    NODE_VERSION = "18"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[checks]
  [checks.bot_status]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/health"
    port = 8080
    timeout = "5s"
    type = "http"
